#################
# HELLO SERVICE CHECK PLAYBOOK #
#################

#check mysql is installed
#check mysql is running
#check hello service is running
---
- name: localcheck
  hosts: "all"
  vars:
    mysql_password: "password"
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: "Check if mysql is installed"
      mysql_info:
        login_user: root
        login_password: "{{ mysql_password }}"
      register: mysql_info
      failed_when: mysql_info is not defined

    - name: "Get services"
      ansible.builtin.service_facts:

    - name: Please use 'msg' when ansible version is smaller than 2.7
      ansible.builtin.assert:
        that:
          - ansible_facts.services['hello.service'].state == 'running'
        msg: "Hello service should be running but it is {{ ansible_facts.services['hello.service'].state }}"
