---
- hosts: all
  become: true

  tasks:
    - name: Add ansible repository.
      ansible.builtin.apt_repository:
        repo: 'ppa:ansible/ansible'
        update_cache: true

    - name: Install Ansible and tools.
      ansible.builtin.apt:
        name: ansible,docker.io,docker-compose
        state: "latest"

    - name: Copy private key
      ansible.builtin.copy:
        src: files/vagrant_test
        dest: /home/vagrant/.ssh/vagrant_test
        owner: vagrant
        group: vagrant
        mode: u=rw,g=,o=

    - name: Copy public key
      ansible.builtin.copy:
        src: files/vagrant_test.pub
        dest: /home/vagrant/.ssh/vagrant_test.pub
        owner: vagrant
        group: vagrant
        mode: u=rw,g=r,o=r