- name: Enable EPEL Repository on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: latest

- name: "Install nginx via yum"
  ansible.builtin.yum:
    name: "nginx"
    state: "latest"
    update_cache: true

- name: "Delete /var/www/html folder"
  ansible.builtin.file:
    name: "/var/www/html"
    state: "absent"

- name: "Copy our landing to /var/www/html folder"
  ansible.builtin.copy:
    src: "files/html"
    dest: "/var/www/"
    owner: "vagrant"
    group: "vagrant"
    mode: "0644"