---
- name: "Check template"
  hosts: "localhost"
  become: false
  gather_facts: false
  vars:
    servers:
    - sname: ranger
      software:
      - ntp
      - nginx
      - http
    - sname: ranger
      software:
      - postgres
      - mysql
    - sname: hunter
      software:
      - webapp
      - loader
      calls:
        name: arg1
        values:
        - run_main
        - run_schedule

  tasks:
  - name: "get template"
    ansible.builtin.template:
      src: "temp.j2"
      dest: "./text.txt"