---
- hosts: "all"
  become: true
  tasks:

  - name: "Delete /var/www/html folder"
    ansible.builtin.file:
      path: "/var/www/html"
      state: "absent"

  - name: "Copy our landing to /var/www/html folder"
    ansible.builtin.copy:
      src: "files/html"
      dest: "/var/www/"
      owner: "vagrant"
      group: "vagrant"
      mode: "0644"

  - name: "Copy nginx config"
    ansible.builtin.copy:
      src: "files/nginx.conf"
      dest: "/etc/nginx/sites-available/mytestsite.conf"
      owner: "vagrant"
      group: "vagrant"
      mode: "0644"

  - name: "Link folder"
    ansible.builtin.file:
      src: "/etc/nginx/sites-available/mytestsite.conf"
      dest: "/etc/nginx/sites-enabled/mytestsite"
      state: "link"

  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"