- name: "Dynamic ec2" # просто пройдемся по инстансам
  hosts: tag_group_web
  gather_facts: true
  gather_subset: min # не собираем больше минимума
  tasks:
    - name: "Show facts"
      ansible.builtin.debug:
        msg: "Facts are {{ansible_facts}}"