#################
# LEMP CHECK PLAYBOOK #
#################
---
- name: localcheck
  hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  tasks: # список тасков

    - name: Checking if website is available and has contents
      ansible.builtin.uri:
        url: http://localhost
        method: GET
        status_code: 200
        return_content: true
        headers:
          Host: "mytestsite.com"
      register: local_contents
      failed_when: "local_contents.status != 200 or 'Choosing an Apple' not in local_contents.content"

- name: remotecheck
  hosts: "localhost"
  connection: local
  tasks:
    - name: Show all the hosts in the inventory
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ groups['all'] }}"

    - name: Checking if website is available and has contents locally
      ansible.builtin.uri:
        url: "http://{{ item }}"
        method: GET
        status_code: 200
        return_content: true
        headers:
          Host: "mytestsite.com"
      register: remote_contents
      failed_when: "remote_contents.status != 200 or 'Choosing an Apple' not in remote_contents.content"
      loop: "{{ groups['all'] }}"