# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision "file", source: "files/vagrant_test.pub", destination: "/home/vagrant/.ssh/"

  config.vm.define "controlnode" do |controlnode|
    controlnode.vm.box = "ubuntu/focal64"
    controlnode.vm.hostname = "controlnode"
    controlnode.vm.network "private_network", ip: "192.168.50.4"
    controlnode.vm.synced_folder "./ansible","/home/vagrant/ansible"
    controlnode.vm.synced_folder "./files","/home/vagrant/files/"
    controlnode.vm.provision "file", source: "files/vagrant_test", destination: "/home/vagrant/.ssh/"
    controlnode.vm.provision "file", source: "files/exclude_from_prod.py", destination: "/home/vagrant/"
    controlnode.vm.provision "file", source: "files/include_to_prod.py", destination: "/home/vagrant/"
    controlnode.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
      service ssh restart
      sudo add-apt-repository ppa:ansible/ansible
      sudo apt update -y && sudo apt -y install sshpass ansible
      chmod 600 /home/vagrant/.ssh/vagrant_test
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
    SHELL
  end

  config.vm.define "server_postgres_master" do |server_postgres_master|
    server_postgres_master.vm.box = "bento/centos-7.9"
    server_postgres_master.vm.hostname = "server-postgres-master"
#    server_postgres_master.vbguest.auto_update = false
    server_postgres_master.vm.network "private_network", ip: "192.168.56.41"
    server_postgres_master.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      chmod 755 /home/vagrant/exclude_from_prod.py
      chmod 755 /home/vagrant/include_to_prod.py
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server_postgres_slave" do |server_postgres_slave|
    server_postgres_slave.vm.box = "bento/centos-7.9"
    server_postgres_slave.vm.hostname = "server-postgres-slave"
#    server_postgres_slave.vbguest.auto_update = false
    server_postgres_slave.vm.network "private_network", ip: "192.168.56.42"
    server_postgres_slave.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server_mongo_primary" do |server_mongo_primary|
    server_mongo_primary.vm.box = "bento/centos-7.9"
    server_mongo_primary.vm.hostname = "server-mongo-primary"
#    server_mongo_primary.vbguest.auto_update = false
    server_mongo_primary.vm.network "private_network", ip: "192.168.52.2"
    server_mongo_primary.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server_mongo_secondary" do |server_mongo_secondary|
    server_mongo_secondary.vm.box = "bento/centos-7.9"
    server_mongo_secondary.vm.hostname = "server-mongo-secondary"
#    server_mongo_secondary.vbguest.auto_update = false
    server_mongo_secondary.vm.network "private_network", ip: "192.168.52.3"
    server_mongo_secondary.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server_mongo_arbiter" do |server_mongo_arbiter|
    server_mongo_arbiter.vm.box = "bento/centos-7.9"
    server_mongo_arbiter.vm.hostname = "server-mongo-arbiter"
#    server_mongo_arbiter.vbguest.auto_update = false
    server_mongo_arbiter.vm.network "private_network", ip: "192.168.52.4"
    server_mongo_arbiter.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

    config.vm.define "server_docker_builder" do |server_docker_builder|
    server_docker_builder.vm.box = "bento/centos-7.9"
    server_docker_builder.vm.hostname = "server-docker-builder"
#    server_docker_builder.vbguest.auto_update = false
    server_docker_builder.vm.network "private_network", ip: "192.168.53.2"
    server_docker_builder.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server_docker_runner" do |server_docker_runner|
    server_docker_runner.vm.box = "bento/centos-7.9"
    server_docker_runner.vm.hostname = "server-docker-runner"
#    server_docker_runner.vbguest.auto_update = false
    server_docker_runner.vm.network "private_network", ip: "192.168.53.3"
    server_docker_runner.vm.provision "shell", inline: <<-SHELL
      chmod 644 /home/vagrant/.ssh/vagrant_test.pub
      cat /home/vagrant/.ssh/vagrant_test.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
