---
- name: Basic group
  hosts: ubuntu
  become: true
  vars:
    test_var: test
    version: 7.0
#    ansible_date_time: notime

  tasks:
  - name: "Test vars"
    ansible.builtin.debug:
      msg: "Variable is set to {{ test_var }} {{ansible_date_time}}"

#  - name: Print the package facts
#    ansible.builtin.debug:
#      var: ansible_facts

  - name: Print debug 7
    ansible.builtin.debug:
      msg: Test php7
    when: version > 7.2 and version < 8.0

  - name: Print debug 8
    ansible.builtin.debug:
      msg: Test php 8
    when:  version >= 8.0
