# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.define "controlnode" do |controlnode|
   controlnode.vm.box = "bento/centos-7.9"
   controlnode.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
   controlnode.vbguest.installer_options = { allow_kernel_upgrade: true }
   controlnode.vm.hostname = "controlnode"
   controlnode.vm.network "private_network", ip: "192.168.50.44"
   controlnode.vm.synced_folder "./ansible","/home/vagrant/ansible"
   controlnode.vm.provision "shell", inline: <<-SHELL
     yum install openssh-server -y
     systemctl start sshd
     sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
     service sshd restart
   SHELL
   controlnode.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 2
   end
 end
 # Every Vagrant development environment requires a box. You can search for
 # boxes at https://vagrantcloud.com/search.
 config.vm.define "server" do |server|
  server.vm.box = "bento/centos-7.9"
  server.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
  server.vbguest.installer_options = { allow_kernel_upgrade: true }
  server.vm.hostname = "server"
  server.vm.network "private_network", ip: "192.168.50.55"
  server.vm.provision "shell", inline: <<-SHELL
    yum install openssh-server -y
    systemctl start sshd
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
    service sshd restart
  SHELL
  server.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
 end
end

