# Main nginx tasks file
- name: Ubuntu tasks
  include_tasks: "ubuntu.yml"
  when: ansible_os_family == "Debian"

- name: Centos tasks
  include_tasks: "centos.yml"
  when: ansible_os_family == "RedHat"

- name: "Reload nginx"
  service:
    name: nginx
    state: reloaded